/**
 * Populate Countries and Cities Database
 *
 * This script populates the apply_countries and apply_cities tables
 * with a comprehensive list of countries and major cities.
 *
 * Uses free, legal data sources:
 * - ISO 3166 country codes
 * - Curated list of major cities with populations
 */

import { query, testConnection } from '../src/models/db';
import { normalizeText } from '../src/services/fuzzyMatcher';

interface CountryData {
  name: string;
  iso2: string;
  iso3: string;
  aliases: string[];
}

interface CityData {
  name: string;
  countryIso2: string;
  adminRegion?: string;
  population?: number;
  latitude?: number;
  longitude?: number;
  aliases?: string[];
}

// Comprehensive country list with aliases
const countries: CountryData[] = [
  {
    name: 'United States',
    iso2: 'US',
    iso3: 'USA',
    aliases: ['USA', 'United States of America', 'America', 'U.S.', 'U.S.A.'],
  },
  {
    name: 'United Kingdom',
    iso2: 'GB',
    iso3: 'GBR',
    aliases: [
      'UK',
      'Britain',
      'Great Britain',
      'England',
      'Scotland',
      'Wales',
      'Northern Ireland',
    ],
  },
  { name: 'Canada', iso2: 'CA', iso3: 'CAN', aliases: [] },
  { name: 'Australia', iso2: 'AU', iso3: 'AUS', aliases: ['AUS'] },
  { name: 'Germany', iso2: 'DE', iso3: 'DEU', aliases: ['Deutschland'] },
  { name: 'France', iso2: 'FR', iso3: 'FRA', aliases: [] },
  { name: 'Italy', iso2: 'IT', iso3: 'ITA', aliases: [] },
  { name: 'Spain', iso2: 'ES', iso3: 'ESP', aliases: ['España'] },
  {
    name: 'Netherlands',
    iso2: 'NL',
    iso3: 'NLD',
    aliases: ['Holland', 'The Netherlands'],
  },
  { name: 'Belgium', iso2: 'BE', iso3: 'BEL', aliases: [] },
  {
    name: 'Switzerland',
    iso2: 'CH',
    iso3: 'CHE',
    aliases: ['Schweiz', 'Suisse', 'Svizzera'],
  },
  { name: 'Austria', iso2: 'AT', iso3: 'AUT', aliases: ['Österreich'] },
  { name: 'Sweden', iso2: 'SE', iso3: 'SWE', aliases: ['Sverige'] },
  { name: 'Norway', iso2: 'NO', iso3: 'NOR', aliases: ['Norge'] },
  { name: 'Denmark', iso2: 'DK', iso3: 'DNK', aliases: ['Danmark'] },
  { name: 'Finland', iso2: 'FI', iso3: 'FIN', aliases: ['Suomi'] },
  { name: 'Ireland', iso2: 'IE', iso3: 'IRL', aliases: ['Éire'] },
  { name: 'New Zealand', iso2: 'NZ', iso3: 'NZL', aliases: [] },
  { name: 'Singapore', iso2: 'SG', iso3: 'SGP', aliases: [] },
  {
    name: 'United Arab Emirates',
    iso2: 'AE',
    iso3: 'ARE',
    aliases: ['UAE', 'Emirates'],
  },
  {
    name: 'Saudi Arabia',
    iso2: 'SA',
    iso3: 'SAU',
    aliases: ['KSA', 'Kingdom of Saudi Arabia'],
  },
  { name: 'Qatar', iso2: 'QA', iso3: 'QAT', aliases: [] },
  { name: 'Kuwait', iso2: 'KW', iso3: 'KWT', aliases: [] },
  { name: 'Bahrain', iso2: 'BH', iso3: 'BHR', aliases: [] },
  { name: 'Oman', iso2: 'OM', iso3: 'OMN', aliases: [] },
  { name: 'Jordan', iso2: 'JO', iso3: 'JOR', aliases: [] },
  { name: 'Lebanon', iso2: 'LB', iso3: 'LBN', aliases: [] },
  { name: 'Egypt', iso2: 'EG', iso3: 'EGY', aliases: [] },
  { name: 'South Africa', iso2: 'ZA', iso3: 'ZAF', aliases: [] },
  { name: 'India', iso2: 'IN', iso3: 'IND', aliases: ['Bharat'] },
  {
    name: 'China',
    iso2: 'CN',
    iso3: 'CHN',
    aliases: ["People's Republic of China", 'PRC'],
  },
  { name: 'Japan', iso2: 'JP', iso3: 'JPN', aliases: [] },
  {
    name: 'South Korea',
    iso2: 'KR',
    iso3: 'KOR',
    aliases: ['Korea', 'Republic of Korea'],
  },
  { name: 'Brazil', iso2: 'BR', iso3: 'BRA', aliases: ['Brasil'] },
  { name: 'Mexico', iso2: 'MX', iso3: 'MEX', aliases: ['México'] },
  { name: 'Argentina', iso2: 'AR', iso3: 'ARG', aliases: [] },
  { name: 'Chile', iso2: 'CL', iso3: 'CHL', aliases: [] },
  { name: 'Colombia', iso2: 'CO', iso3: 'COL', aliases: [] },
  { name: 'Poland', iso2: 'PL', iso3: 'POL', aliases: ['Polska'] },
  { name: 'Portugal', iso2: 'PT', iso3: 'PRT', aliases: [] },
  { name: 'Greece', iso2: 'GR', iso3: 'GRC', aliases: ['Hellas'] },
  { name: 'Turkey', iso2: 'TR', iso3: 'TUR', aliases: ['Türkiye'] },
  { name: 'Russia', iso2: 'RU', iso3: 'RUS', aliases: ['Russian Federation'] },
  { name: 'Ukraine', iso2: 'UA', iso3: 'UKR', aliases: [] },
  { name: 'Czech Republic', iso2: 'CZ', iso3: 'CZE', aliases: ['Czechia'] },
  { name: 'Hungary', iso2: 'HU', iso3: 'HUN', aliases: ['Magyarország'] },
  { name: 'Romania', iso2: 'RO', iso3: 'ROU', aliases: [] },
  { name: 'Bulgaria', iso2: 'BG', iso3: 'BGR', aliases: [] },
  { name: 'Croatia', iso2: 'HR', iso3: 'HRV', aliases: ['Hrvatska'] },
  { name: 'Serbia', iso2: 'RS', iso3: 'SRB', aliases: ['Srbija'] },
  { name: 'Slovakia', iso2: 'SK', iso3: 'SVK', aliases: ['Slovensko'] },
  { name: 'Slovenia', iso2: 'SI', iso3: 'SVN', aliases: ['Slovenija'] },
  { name: 'Estonia', iso2: 'EE', iso3: 'EST', aliases: ['Eesti'] },
  { name: 'Latvia', iso2: 'LV', iso3: 'LVA', aliases: ['Latvija'] },
  { name: 'Lithuania', iso2: 'LT', iso3: 'LTU', aliases: ['Lietuva'] },
  { name: 'Luxembourg', iso2: 'LU', iso3: 'LUX', aliases: [] },
  { name: 'Iceland', iso2: 'IS', iso3: 'ISL', aliases: ['Ísland'] },
  { name: 'Malta', iso2: 'MT', iso3: 'MLT', aliases: [] },
  { name: 'Cyprus', iso2: 'CY', iso3: 'CYP', aliases: [] },
  { name: 'Malaysia', iso2: 'MY', iso3: 'MYS', aliases: [] },
  { name: 'Thailand', iso2: 'TH', iso3: 'THA', aliases: [] },
  { name: 'Indonesia', iso2: 'ID', iso3: 'IDN', aliases: [] },
  { name: 'Philippines', iso2: 'PH', iso3: 'PHL', aliases: [] },
  { name: 'Vietnam', iso2: 'VN', iso3: 'VNM', aliases: ['Việt Nam'] },
  { name: 'Taiwan', iso2: 'TW', iso3: 'TWN', aliases: ['Republic of China'] },
  { name: 'Hong Kong', iso2: 'HK', iso3: 'HKG', aliases: ['Hong Kong SAR'] },
  { name: 'Pakistan', iso2: 'PK', iso3: 'PAK', aliases: [] },
  { name: 'Bangladesh', iso2: 'BD', iso3: 'BGD', aliases: [] },
  { name: 'Sri Lanka', iso2: 'LK', iso3: 'LKA', aliases: [] },
  { name: 'Nepal', iso2: 'NP', iso3: 'NPL', aliases: [] },
  { name: 'Myanmar', iso2: 'MM', iso3: 'MMR', aliases: ['Burma'] },
  { name: 'Cambodia', iso2: 'KH', iso3: 'KHM', aliases: [] },
  { name: 'Laos', iso2: 'LA', iso3: 'LAO', aliases: ['Lao PDR'] },
  { name: 'Mongolia', iso2: 'MN', iso3: 'MNG', aliases: [] },
  { name: 'Kazakhstan', iso2: 'KZ', iso3: 'KAZ', aliases: ['Qazaqstan'] },
  { name: 'Uzbekistan', iso2: 'UZ', iso3: 'UZB', aliases: [] },
  { name: 'Azerbaijan', iso2: 'AZ', iso3: 'AZE', aliases: [] },
  { name: 'Georgia', iso2: 'GE', iso3: 'GEO', aliases: [] },
  { name: 'Armenia', iso2: 'AM', iso3: 'ARM', aliases: [] },
  {
    name: 'Iran',
    iso2: 'IR',
    iso3: 'IRN',
    aliases: ['Islamic Republic of Iran'],
  },
  { name: 'Iraq', iso2: 'IQ', iso3: 'IRQ', aliases: [] },
  { name: 'Syria', iso2: 'SY', iso3: 'SYR', aliases: [] },
  { name: 'Yemen', iso2: 'YE', iso3: 'YEM', aliases: [] },
  {
    name: 'Palestine',
    iso2: 'PS',
    iso3: 'PSE',
    aliases: ['State of Palestine', 'Palestinian Territories'],
  },
  { name: 'Morocco', iso2: 'MA', iso3: 'MAR', aliases: [] },
  { name: 'Algeria', iso2: 'DZ', iso3: 'DZA', aliases: [] },
  { name: 'Tunisia', iso2: 'TN', iso3: 'TUN', aliases: [] },
  { name: 'Libya', iso2: 'LY', iso3: 'LBY', aliases: [] },
  { name: 'Sudan', iso2: 'SD', iso3: 'SDN', aliases: [] },
  { name: 'Ethiopia', iso2: 'ET', iso3: 'ETH', aliases: [] },
  { name: 'Kenya', iso2: 'KE', iso3: 'KEN', aliases: [] },
  { name: 'Tanzania', iso2: 'TZ', iso3: 'TZA', aliases: [] },
  { name: 'Uganda', iso2: 'UG', iso3: 'UGA', aliases: [] },
  { name: 'Ghana', iso2: 'GH', iso3: 'GHA', aliases: [] },
  { name: 'Nigeria', iso2: 'NG', iso3: 'NGA', aliases: [] },
  { name: 'Senegal', iso2: 'SN', iso3: 'SEN', aliases: [] },
  { name: 'Ivory Coast', iso2: 'CI', iso3: 'CIV', aliases: ["Côte d'Ivoire"] },
  { name: 'Cameroon', iso2: 'CM', iso3: 'CMR', aliases: [] },
  { name: 'Angola', iso2: 'AO', iso3: 'AGO', aliases: [] },
  { name: 'Mozambique', iso2: 'MZ', iso3: 'MOZ', aliases: [] },
  { name: 'Madagascar', iso2: 'MG', iso3: 'MDG', aliases: [] },
  { name: 'Mauritius', iso2: 'MU', iso3: 'MUS', aliases: [] },
  { name: 'Seychelles', iso2: 'SC', iso3: 'SYC', aliases: [] },
  { name: 'Peru', iso2: 'PE', iso3: 'PER', aliases: ['Perú'] },
  { name: 'Ecuador', iso2: 'EC', iso3: 'ECU', aliases: [] },
  { name: 'Venezuela', iso2: 'VE', iso3: 'VEN', aliases: [] },
  { name: 'Uruguay', iso2: 'UY', iso3: 'URY', aliases: [] },
  { name: 'Paraguay', iso2: 'PY', iso3: 'PRY', aliases: [] },
  { name: 'Bolivia', iso2: 'BO', iso3: 'BOL', aliases: [] },
  { name: 'Panama', iso2: 'PA', iso3: 'PAN', aliases: [] },
  { name: 'Costa Rica', iso2: 'CR', iso3: 'CRI', aliases: [] },
  { name: 'Guatemala', iso2: 'GT', iso3: 'GTM', aliases: [] },
  { name: 'Honduras', iso2: 'HN', iso3: 'HND', aliases: [] },
  { name: 'El Salvador', iso2: 'SV', iso3: 'SLV', aliases: [] },
  { name: 'Nicaragua', iso2: 'NI', iso3: 'NIC', aliases: [] },
  { name: 'Dominican Republic', iso2: 'DO', iso3: 'DOM', aliases: [] },
  { name: 'Jamaica', iso2: 'JM', iso3: 'JAM', aliases: [] },
  { name: 'Trinidad and Tobago', iso2: 'TT', iso3: 'TTO', aliases: [] },
  { name: 'Barbados', iso2: 'BB', iso3: 'BRB', aliases: [] },
  { name: 'Bahamas', iso2: 'BS', iso3: 'BHS', aliases: [] },
];

// Major cities with approximate populations and coordinates
const cities: CityData[] = [
  // United States
  {
    name: 'New York',
    countryIso2: 'US',
    adminRegion: 'New York',
    population: 8336817,
    latitude: 40.7128,
    longitude: -74.006,
    aliases: ['NYC', 'New York City'],
  },
  {
    name: 'Los Angeles',
    countryIso2: 'US',
    adminRegion: 'California',
    population: 3971883,
    latitude: 34.0522,
    longitude: -118.2437,
    aliases: ['LA', 'L.A.'],
  },
  {
    name: 'Chicago',
    countryIso2: 'US',
    adminRegion: 'Illinois',
    population: 2693976,
    latitude: 41.8781,
    longitude: -87.6298,
  },
  {
    name: 'Houston',
    countryIso2: 'US',
    adminRegion: 'Texas',
    population: 2320268,
    latitude: 29.7604,
    longitude: -95.3698,
  },
  {
    name: 'Phoenix',
    countryIso2: 'US',
    adminRegion: 'Arizona',
    population: 1680992,
    latitude: 33.4484,
    longitude: -112.074,
  },
  {
    name: 'Philadelphia',
    countryIso2: 'US',
    adminRegion: 'Pennsylvania',
    population: 1584064,
    latitude: 39.9526,
    longitude: -75.1652,
    aliases: ['Philly'],
  },
  {
    name: 'San Antonio',
    countryIso2: 'US',
    adminRegion: 'Texas',
    population: 1547253,
    latitude: 29.4241,
    longitude: -98.4936,
  },
  {
    name: 'San Diego',
    countryIso2: 'US',
    adminRegion: 'California',
    population: 1423851,
    latitude: 32.7157,
    longitude: -117.1611,
  },
  {
    name: 'Dallas',
    countryIso2: 'US',
    adminRegion: 'Texas',
    population: 1343573,
    latitude: 32.7767,
    longitude: -96.797,
  },
  {
    name: 'San Jose',
    countryIso2: 'US',
    adminRegion: 'California',
    population: 1021795,
    latitude: 37.3382,
    longitude: -121.8863,
  },
  {
    name: 'Austin',
    countryIso2: 'US',
    adminRegion: 'Texas',
    population: 978908,
    latitude: 30.2672,
    longitude: -97.7431,
  },
  {
    name: 'Jacksonville',
    countryIso2: 'US',
    adminRegion: 'Florida',
    population: 949611,
    latitude: 30.3322,
    longitude: -81.6557,
  },
  {
    name: 'San Francisco',
    countryIso2: 'US',
    adminRegion: 'California',
    population: 873965,
    latitude: 37.7749,
    longitude: -122.4194,
    aliases: ['SF', 'San Fran'],
  },
  {
    name: 'Seattle',
    countryIso2: 'US',
    adminRegion: 'Washington',
    population: 753675,
    latitude: 47.6062,
    longitude: -122.3321,
  },
  {
    name: 'Boston',
    countryIso2: 'US',
    adminRegion: 'Massachusetts',
    population: 692600,
    latitude: 42.3601,
    longitude: -71.0589,
  },
  {
    name: 'Denver',
    countryIso2: 'US',
    adminRegion: 'Colorado',
    population: 715522,
    latitude: 39.7392,
    longitude: -104.9903,
  },
  {
    name: 'Washington',
    countryIso2: 'US',
    adminRegion: 'District of Columbia',
    population: 705749,
    latitude: 38.9072,
    longitude: -77.0369,
    aliases: ['Washington DC', 'DC', 'Washington D.C.'],
  },
  {
    name: 'Miami',
    countryIso2: 'US',
    adminRegion: 'Florida',
    population: 442241,
    latitude: 25.7617,
    longitude: -80.1918,
  },
  {
    name: 'Atlanta',
    countryIso2: 'US',
    adminRegion: 'Georgia',
    population: 498715,
    latitude: 33.749,
    longitude: -84.388,
  },
  {
    name: 'Portland',
    countryIso2: 'US',
    adminRegion: 'Oregon',
    population: 652503,
    latitude: 45.5152,
    longitude: -122.6784,
  },

  // United Kingdom
  {
    name: 'London',
    countryIso2: 'GB',
    adminRegion: 'England',
    population: 8982000,
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    name: 'Manchester',
    countryIso2: 'GB',
    adminRegion: 'England',
    population: 547627,
    latitude: 53.4808,
    longitude: -2.2426,
  },
  {
    name: 'Birmingham',
    countryIso2: 'GB',
    adminRegion: 'England',
    population: 1141816,
    latitude: 52.4862,
    longitude: -1.8904,
  },
  {
    name: 'Glasgow',
    countryIso2: 'GB',
    adminRegion: 'Scotland',
    population: 612040,
    latitude: 55.8642,
    longitude: -4.2518,
  },
  {
    name: 'Edinburgh',
    countryIso2: 'GB',
    adminRegion: 'Scotland',
    population: 524930,
    latitude: 55.9533,
    longitude: -3.1883,
  },
  {
    name: 'Liverpool',
    countryIso2: 'GB',
    adminRegion: 'England',
    population: 494814,
    latitude: 53.4084,
    longitude: -2.9916,
  },
  {
    name: 'Leeds',
    countryIso2: 'GB',
    adminRegion: 'England',
    population: 789194,
    latitude: 53.8008,
    longitude: -1.5491,
  },
  {
    name: 'Bristol',
    countryIso2: 'GB',
    adminRegion: 'England',
    population: 463400,
    latitude: 51.4545,
    longitude: -2.5879,
  },
  {
    name: 'Cardiff',
    countryIso2: 'GB',
    adminRegion: 'Wales',
    population: 362310,
    latitude: 51.4816,
    longitude: -3.1791,
  },
  {
    name: 'Belfast',
    countryIso2: 'GB',
    adminRegion: 'Northern Ireland',
    population: 343542,
    latitude: 54.5973,
    longitude: -5.9301,
  },

  // Canada
  {
    name: 'Toronto',
    countryIso2: 'CA',
    adminRegion: 'Ontario',
    population: 2930000,
    latitude: 43.6532,
    longitude: -79.3832,
  },
  {
    name: 'Vancouver',
    countryIso2: 'CA',
    adminRegion: 'British Columbia',
    population: 675218,
    latitude: 49.2827,
    longitude: -123.1207,
  },
  {
    name: 'Montreal',
    countryIso2: 'CA',
    adminRegion: 'Quebec',
    population: 1780000,
    latitude: 45.5017,
    longitude: -73.5673,
  },
  {
    name: 'Calgary',
    countryIso2: 'CA',
    adminRegion: 'Alberta',
    population: 1306784,
    latitude: 51.0447,
    longitude: -114.0719,
  },
  {
    name: 'Ottawa',
    countryIso2: 'CA',
    adminRegion: 'Ontario',
    population: 1017449,
    latitude: 45.4215,
    longitude: -75.6972,
  },
  {
    name: 'Edmonton',
    countryIso2: 'CA',
    adminRegion: 'Alberta',
    population: 1010899,
    latitude: 53.5461,
    longitude: -113.4938,
  },
  {
    name: 'Winnipeg',
    countryIso2: 'CA',
    adminRegion: 'Manitoba',
    population: 749607,
    latitude: 49.8951,
    longitude: -97.1384,
  },
  {
    name: 'Quebec City',
    countryIso2: 'CA',
    adminRegion: 'Quebec',
    population: 549459,
    latitude: 46.8139,
    longitude: -71.208,
    aliases: ['Québec'],
  },
  {
    name: 'Hamilton',
    countryIso2: 'CA',
    adminRegion: 'Ontario',
    population: 569353,
    latitude: 43.2557,
    longitude: -79.8711,
  },
  {
    name: 'Kitchener',
    countryIso2: 'CA',
    adminRegion: 'Ontario',
    population: 256885,
    latitude: 43.4516,
    longitude: -80.4925,
  },

  // Australia
  {
    name: 'Sydney',
    countryIso2: 'AU',
    adminRegion: 'New South Wales',
    population: 5312163,
    latitude: -33.8688,
    longitude: 151.2093,
  },
  {
    name: 'Melbourne',
    countryIso2: 'AU',
    adminRegion: 'Victoria',
    population: 5078193,
    latitude: -37.8136,
    longitude: 144.9631,
  },
  {
    name: 'Brisbane',
    countryIso2: 'AU',
    adminRegion: 'Queensland',
    population: 2564960,
    latitude: -27.4698,
    longitude: 153.0251,
  },
  {
    name: 'Perth',
    countryIso2: 'AU',
    adminRegion: 'Western Australia',
    population: 2141987,
    latitude: -31.9505,
    longitude: 115.8605,
  },
  {
    name: 'Adelaide',
    countryIso2: 'AU',
    adminRegion: 'South Australia',
    population: 1356535,
    latitude: -34.9285,
    longitude: 138.6007,
  },
  {
    name: 'Gold Coast',
    countryIso2: 'AU',
    adminRegion: 'Queensland',
    population: 709721,
    latitude: -28.0167,
    longitude: 153.4,
  },
  {
    name: 'Newcastle',
    countryIso2: 'AU',
    adminRegion: 'New South Wales',
    population: 322278,
    latitude: -32.9283,
    longitude: 151.7817,
  },
  {
    name: 'Canberra',
    countryIso2: 'AU',
    adminRegion: 'Australian Capital Territory',
    population: 462136,
    latitude: -35.2809,
    longitude: 149.13,
  },
  {
    name: 'Sunshine Coast',
    countryIso2: 'AU',
    adminRegion: 'Queensland',
    population: 348614,
    latitude: -26.65,
    longitude: 153.0667,
  },
  {
    name: 'Wollongong',
    countryIso2: 'AU',
    adminRegion: 'New South Wales',
    population: 302739,
    latitude: -34.4278,
    longitude: 150.8931,
  },

  // Middle East
  {
    name: 'Dubai',
    countryIso2: 'AE',
    adminRegion: 'Dubai',
    population: 3400000,
    latitude: 25.2048,
    longitude: 55.2708,
    aliases: ['Dubayy'],
  },
  {
    name: 'Abu Dhabi',
    countryIso2: 'AE',
    adminRegion: 'Abu Dhabi',
    population: 1450000,
    latitude: 24.4539,
    longitude: 54.3773,
  },
  {
    name: 'Riyadh',
    countryIso2: 'SA',
    adminRegion: 'Riyadh',
    population: 7700000,
    latitude: 24.7136,
    longitude: 46.6753,
  },
  {
    name: 'Jeddah',
    countryIso2: 'SA',
    adminRegion: 'Makkah',
    population: 4700000,
    latitude: 21.4858,
    longitude: 39.1925,
  },
  {
    name: 'Dammam',
    countryIso2: 'SA',
    adminRegion: 'Eastern Province',
    population: 1200000,
    latitude: 26.4207,
    longitude: 50.0888,
  },
  {
    name: 'Amman',
    countryIso2: 'JO',
    adminRegion: 'Amman',
    population: 4007526,
    latitude: 31.9539,
    longitude: 35.9106,
    aliases: ['ammman'],
  },
  {
    name: 'Irbid',
    countryIso2: 'JO',
    adminRegion: 'Irbid',
    population: 650000,
    latitude: 32.5556,
    longitude: 35.85,
  },
  {
    name: 'Zarqa',
    countryIso2: 'JO',
    adminRegion: 'Zarqa',
    population: 635160,
    latitude: 32.0753,
    longitude: 36.0875,
  },
  {
    name: 'Beirut',
    countryIso2: 'LB',
    adminRegion: 'Beirut',
    population: 2400000,
    latitude: 33.8938,
    longitude: 35.5018,
  },
  {
    name: 'Tel Aviv',
    countryIso2: 'PS',
    adminRegion: 'Tel Aviv',
    population: 460613,
    latitude: 32.0853,
    longitude: 34.7818,
    aliases: ['Tel Aviv-Yafo'],
  },
  {
    name: 'Jerusalem',
    countryIso2: 'PS',
    adminRegion: 'Jerusalem',
    population: 936425,
    latitude: 31.7683,
    longitude: 35.2137,
  },
  {
    name: 'Haifa',
    countryIso2: 'PS',
    adminRegion: 'Haifa',
    population: 285316,
    latitude: 32.794,
    longitude: 34.9896,
  },
  {
    name: 'Doha',
    countryIso2: 'QA',
    adminRegion: 'Doha',
    population: 956460,
    latitude: 25.2854,
    longitude: 51.531,
  },
  {
    name: 'Kuwait City',
    countryIso2: 'KW',
    adminRegion: 'Kuwait',
    population: 3000000,
    latitude: 29.3759,
    longitude: 47.9774,
    aliases: ['Kuwait'],
  },
  {
    name: 'Manama',
    countryIso2: 'BH',
    adminRegion: 'Capital',
    population: 200000,
    latitude: 26.0667,
    longitude: 50.5577,
  },
  {
    name: 'Muscat',
    countryIso2: 'OM',
    adminRegion: 'Muscat',
    population: 1421409,
    latitude: 23.5859,
    longitude: 58.4059,
  },
  {
    name: 'Cairo',
    countryIso2: 'EG',
    adminRegion: 'Cairo',
    population: 10230350,
    latitude: 30.0444,
    longitude: 31.2357,
  },
  {
    name: 'Alexandria',
    countryIso2: 'EG',
    adminRegion: 'Alexandria',
    population: 5200000,
    latitude: 31.2001,
    longitude: 29.9187,
  },
  {
    name: 'Ramallah',
    countryIso2: 'PS',
    adminRegion: 'West Bank',
    population: 35000,
    latitude: 31.9073,
    longitude: 35.2043,
  },
  {
    name: 'Gaza',
    countryIso2: 'PS',
    adminRegion: 'Gaza Strip',
    population: 590000,
    latitude: 31.3547,
    longitude: 34.3088,
    aliases: ['Gaza City'],
  },

  // Europe
  {
    name: 'Berlin',
    countryIso2: 'DE',
    adminRegion: 'Berlin',
    population: 3669491,
    latitude: 52.52,
    longitude: 13.405,
  },
  {
    name: 'Munich',
    countryIso2: 'DE',
    adminRegion: 'Bavaria',
    population: 1488202,
    latitude: 48.1351,
    longitude: 11.582,
    aliases: ['München'],
  },
  {
    name: 'Hamburg',
    countryIso2: 'DE',
    adminRegion: 'Hamburg',
    population: 1841179,
    latitude: 53.5511,
    longitude: 9.9937,
  },
  {
    name: 'Frankfurt',
    countryIso2: 'DE',
    adminRegion: 'Hesse',
    population: 763380,
    latitude: 50.1109,
    longitude: 8.6821,
    aliases: ['Frankfurt am Main'],
  },
  {
    name: 'Cologne',
    countryIso2: 'DE',
    adminRegion: 'North Rhine-Westphalia',
    population: 1085664,
    latitude: 50.9375,
    longitude: 6.9603,
    aliases: ['Köln'],
  },
  {
    name: 'Paris',
    countryIso2: 'FR',
    adminRegion: 'Île-de-France',
    population: 2161000,
    latitude: 48.8566,
    longitude: 2.3522,
  },
  {
    name: 'Lyon',
    countryIso2: 'FR',
    adminRegion: 'Auvergne-Rhône-Alpes',
    population: 516092,
    latitude: 45.764,
    longitude: 4.8357,
  },
  {
    name: 'Marseille',
    countryIso2: 'FR',
    adminRegion: "Provence-Alpes-Côte d'Azur",
    population: 870731,
    latitude: 43.2965,
    longitude: 5.3698,
  },
  {
    name: 'Toulouse',
    countryIso2: 'FR',
    adminRegion: 'Occitanie',
    population: 493465,
    latitude: 43.6047,
    longitude: 1.4442,
  },
  {
    name: 'Nice',
    countryIso2: 'FR',
    adminRegion: "Provence-Alpes-Côte d'Azur",
    population: 340017,
    latitude: 43.7102,
    longitude: 7.262,
  },
  {
    name: 'Rome',
    countryIso2: 'IT',
    adminRegion: 'Lazio',
    population: 2873000,
    latitude: 41.9028,
    longitude: 12.4964,
    aliases: ['Roma'],
  },
  {
    name: 'Milan',
    countryIso2: 'IT',
    adminRegion: 'Lombardy',
    population: 1399860,
    latitude: 45.4642,
    longitude: 9.19,
    aliases: ['Milano'],
  },
  {
    name: 'Naples',
    countryIso2: 'IT',
    adminRegion: 'Campania',
    population: 967069,
    latitude: 40.8518,
    longitude: 14.2681,
    aliases: ['Napoli'],
  },
  {
    name: 'Turin',
    countryIso2: 'IT',
    adminRegion: 'Piedmont',
    population: 870952,
    latitude: 45.0703,
    longitude: 7.6869,
    aliases: ['Torino'],
  },
  {
    name: 'Florence',
    countryIso2: 'IT',
    adminRegion: 'Tuscany',
    population: 382258,
    latitude: 43.7696,
    longitude: 11.2558,
    aliases: ['Firenze'],
  },
  {
    name: 'Madrid',
    countryIso2: 'ES',
    adminRegion: 'Madrid',
    population: 3223334,
    latitude: 40.4168,
    longitude: -3.7038,
  },
  {
    name: 'Barcelona',
    countryIso2: 'ES',
    adminRegion: 'Catalonia',
    population: 1636762,
    latitude: 41.3851,
    longitude: 2.1734,
  },
  {
    name: 'Valencia',
    countryIso2: 'ES',
    adminRegion: 'Valencia',
    population: 789744,
    latitude: 39.4699,
    longitude: -0.3763,
  },
  {
    name: 'Seville',
    countryIso2: 'ES',
    adminRegion: 'Andalusia',
    population: 684234,
    latitude: 37.3891,
    longitude: -5.9845,
    aliases: ['Sevilla'],
  },
  {
    name: 'Amsterdam',
    countryIso2: 'NL',
    adminRegion: 'North Holland',
    population: 872680,
    latitude: 52.3676,
    longitude: 4.9041,
  },
  {
    name: 'Rotterdam',
    countryIso2: 'NL',
    adminRegion: 'South Holland',
    population: 651446,
    latitude: 51.9244,
    longitude: 4.4777,
  },
  {
    name: 'The Hague',
    countryIso2: 'NL',
    adminRegion: 'South Holland',
    population: 548320,
    latitude: 52.0705,
    longitude: 4.3007,
    aliases: ['Den Haag', 's-Gravenhage'],
  },
  {
    name: 'Utrecht',
    countryIso2: 'NL',
    adminRegion: 'Utrecht',
    population: 361924,
    latitude: 52.0907,
    longitude: 5.1214,
  },
  {
    name: 'Brussels',
    countryIso2: 'BE',
    adminRegion: 'Brussels-Capital Region',
    population: 1218255,
    latitude: 50.8503,
    longitude: 4.3517,
    aliases: ['Bruxelles', 'Brussel'],
  },
  {
    name: 'Antwerp',
    countryIso2: 'BE',
    adminRegion: 'Flanders',
    population: 529247,
    latitude: 51.2194,
    longitude: 4.4025,
    aliases: ['Antwerpen'],
  },
  {
    name: 'Zurich',
    countryIso2: 'CH',
    adminRegion: 'Zurich',
    population: 434335,
    latitude: 47.3769,
    longitude: 8.5417,
    aliases: ['Zürich'],
  },
  {
    name: 'Geneva',
    countryIso2: 'CH',
    adminRegion: 'Geneva',
    population: 201818,
    latitude: 46.2044,
    longitude: 6.1432,
    aliases: ['Genève'],
  },
  {
    name: 'Basel',
    countryIso2: 'CH',
    adminRegion: 'Basel-Stadt',
    population: 177595,
    latitude: 47.5596,
    longitude: 7.5886,
  },
  {
    name: 'Vienna',
    countryIso2: 'AT',
    adminRegion: 'Vienna',
    population: 1920949,
    latitude: 48.2082,
    longitude: 16.3738,
    aliases: ['Wien'],
  },
  {
    name: 'Stockholm',
    countryIso2: 'SE',
    adminRegion: 'Stockholm',
    population: 975551,
    latitude: 59.3293,
    longitude: 18.0686,
  },
  {
    name: 'Gothenburg',
    countryIso2: 'SE',
    adminRegion: 'Västra Götaland',
    population: 607882,
    latitude: 57.7089,
    longitude: 11.9746,
    aliases: ['Göteborg'],
  },
  {
    name: 'Oslo',
    countryIso2: 'NO',
    adminRegion: 'Oslo',
    population: 697010,
    latitude: 59.9139,
    longitude: 10.7522,
  },
  {
    name: 'Copenhagen',
    countryIso2: 'DK',
    adminRegion: 'Capital Region',
    population: 644431,
    latitude: 55.6761,
    longitude: 12.5683,
    aliases: ['København'],
  },
  {
    name: 'Helsinki',
    countryIso2: 'FI',
    adminRegion: 'Uusimaa',
    population: 656229,
    latitude: 60.1699,
    longitude: 24.9384,
    aliases: ['Helsingfors'],
  },
  {
    name: 'Dublin',
    countryIso2: 'IE',
    adminRegion: 'Leinster',
    population: 1173179,
    latitude: 53.3498,
    longitude: -6.2603,
  },
  {
    name: 'Cork',
    countryIso2: 'IE',
    adminRegion: 'Munster',
    population: 210000,
    latitude: 51.8985,
    longitude: -8.4756,
  },
  {
    name: 'Warsaw',
    countryIso2: 'PL',
    adminRegion: 'Mazovia',
    population: 1793579,
    latitude: 52.2297,
    longitude: 21.0122,
    aliases: ['Warszawa'],
  },
  {
    name: 'Krakow',
    countryIso2: 'PL',
    adminRegion: 'Lesser Poland',
    population: 779115,
    latitude: 50.0647,
    longitude: 19.945,
    aliases: ['Kraków'],
  },
  {
    name: 'Lisbon',
    countryIso2: 'PT',
    adminRegion: 'Lisbon',
    population: 547733,
    latitude: 38.7223,
    longitude: -9.1393,
    aliases: ['Lisboa'],
  },
  {
    name: 'Porto',
    countryIso2: 'PT',
    adminRegion: 'Porto',
    population: 237591,
    latitude: 41.1579,
    longitude: -8.6291,
  },
  {
    name: 'Athens',
    countryIso2: 'GR',
    adminRegion: 'Attica',
    population: 664046,
    latitude: 37.9838,
    longitude: 23.7275,
    aliases: ['Athína'],
  },
  {
    name: 'Istanbul',
    countryIso2: 'TR',
    adminRegion: 'Istanbul',
    population: 15519267,
    latitude: 41.0082,
    longitude: 28.9784,
  },
  {
    name: 'Ankara',
    countryIso2: 'TR',
    adminRegion: 'Ankara',
    population: 5663322,
    latitude: 39.9334,
    longitude: 32.8597,
  },
  {
    name: 'Moscow',
    countryIso2: 'RU',
    adminRegion: 'Moscow',
    population: 12615279,
    latitude: 55.7558,
    longitude: 37.6173,
    aliases: ['Moskva'],
  },
  {
    name: 'Saint Petersburg',
    countryIso2: 'RU',
    adminRegion: 'Saint Petersburg',
    population: 5384342,
    latitude: 59.9343,
    longitude: 30.3351,
    aliases: ['St. Petersburg', 'Leningrad'],
  },
  {
    name: 'Kyiv',
    countryIso2: 'UA',
    adminRegion: 'Kyiv',
    population: 2962180,
    latitude: 50.4501,
    longitude: 30.5234,
    aliases: ['Kiev'],
  },
  {
    name: 'Prague',
    countryIso2: 'CZ',
    adminRegion: 'Prague',
    population: 1301132,
    latitude: 50.0755,
    longitude: 14.4378,
    aliases: ['Praha'],
  },
  {
    name: 'Budapest',
    countryIso2: 'HU',
    adminRegion: 'Budapest',
    population: 1752286,
    latitude: 47.4979,
    longitude: 19.0402,
  },
  {
    name: 'Bucharest',
    countryIso2: 'RO',
    adminRegion: 'Bucharest',
    population: 1883425,
    latitude: 44.4268,
    longitude: 26.1025,
  },
  {
    name: 'Sofia',
    countryIso2: 'BG',
    adminRegion: 'Sofia',
    population: 1286383,
    latitude: 42.6977,
    longitude: 23.3219,
  },
  {
    name: 'Zagreb',
    countryIso2: 'HR',
    adminRegion: 'Zagreb',
    population: 806341,
    latitude: 45.815,
    longitude: 15.9819,
  },
  {
    name: 'Belgrade',
    countryIso2: 'RS',
    adminRegion: 'Belgrade',
    population: 1378682,
    latitude: 44.7866,
    longitude: 20.4489,
    aliases: ['Beograd'],
  },
  {
    name: 'Bratislava',
    countryIso2: 'SK',
    adminRegion: 'Bratislava',
    population: 475503,
    latitude: 48.1486,
    longitude: 17.1077,
  },
  {
    name: 'Ljubljana',
    countryIso2: 'SI',
    adminRegion: 'Ljubljana',
    population: 295504,
    latitude: 46.0569,
    longitude: 14.5058,
  },
  {
    name: 'Tallinn',
    countryIso2: 'EE',
    adminRegion: 'Harju',
    population: 437619,
    latitude: 59.437,
    longitude: 24.7536,
  },
  {
    name: 'Riga',
    countryIso2: 'LV',
    adminRegion: 'Riga',
    population: 614618,
    latitude: 56.9496,
    longitude: 24.1052,
  },
  {
    name: 'Vilnius',
    countryIso2: 'LT',
    adminRegion: 'Vilnius',
    population: 580020,
    latitude: 54.6872,
    longitude: 25.2797,
  },
  {
    name: 'Luxembourg',
    countryIso2: 'LU',
    adminRegion: 'Luxembourg',
    population: 128514,
    latitude: 49.6116,
    longitude: 6.1319,
    aliases: ['Luxembourg City'],
  },
  {
    name: 'Reykjavik',
    countryIso2: 'IS',
    adminRegion: 'Capital Region',
    population: 131136,
    latitude: 64.1466,
    longitude: -21.9426,
    aliases: ['Reykjavík'],
  },
  {
    name: 'Valletta',
    countryIso2: 'MT',
    adminRegion: 'Malta',
    population: 6444,
    latitude: 35.8989,
    longitude: 14.5146,
  },
  {
    name: 'Nicosia',
    countryIso2: 'CY',
    adminRegion: 'Nicosia',
    population: 200452,
    latitude: 35.1856,
    longitude: 33.3823,
    aliases: ['Lefkosia'],
  },

  // Asia
  {
    name: 'Tokyo',
    countryIso2: 'JP',
    adminRegion: 'Tokyo',
    population: 13929286,
    latitude: 35.6762,
    longitude: 139.6503,
  },
  {
    name: 'Yokohama',
    countryIso2: 'JP',
    adminRegion: 'Kanagawa',
    population: 3770633,
    latitude: 35.4437,
    longitude: 139.638,
  },
  {
    name: 'Osaka',
    countryIso2: 'JP',
    adminRegion: 'Osaka',
    population: 2691185,
    latitude: 34.6937,
    longitude: 135.5023,
  },
  {
    name: 'Kyoto',
    countryIso2: 'JP',
    adminRegion: 'Kyoto',
    population: 1464890,
    latitude: 35.0116,
    longitude: 135.7681,
  },
  {
    name: 'Seoul',
    countryIso2: 'KR',
    adminRegion: 'Seoul',
    population: 9720846,
    latitude: 37.5665,
    longitude: 126.978,
  },
  {
    name: 'Busan',
    countryIso2: 'KR',
    adminRegion: 'Busan',
    population: 3448737,
    latitude: 35.1796,
    longitude: 129.0756,
  },
  {
    name: 'Shanghai',
    countryIso2: 'CN',
    adminRegion: 'Shanghai',
    population: 24870895,
    latitude: 31.2304,
    longitude: 121.4737,
  },
  {
    name: 'Beijing',
    countryIso2: 'CN',
    adminRegion: 'Beijing',
    population: 21540000,
    latitude: 39.9042,
    longitude: 116.4074,
    aliases: ['Peking'],
  },
  {
    name: 'Guangzhou',
    countryIso2: 'CN',
    adminRegion: 'Guangdong',
    population: 14904400,
    latitude: 23.1291,
    longitude: 113.2644,
    aliases: ['Canton'],
  },
  {
    name: 'Shenzhen',
    countryIso2: 'CN',
    adminRegion: 'Guangdong',
    population: 12528359,
    latitude: 22.5431,
    longitude: 114.0579,
  },
  {
    name: 'Hong Kong',
    countryIso2: 'HK',
    adminRegion: 'Hong Kong',
    population: 7507000,
    latitude: 22.3193,
    longitude: 114.1694,
  },
  {
    name: 'Singapore',
    countryIso2: 'SG',
    adminRegion: 'Singapore',
    population: 5685807,
    latitude: 1.3521,
    longitude: 103.8198,
  },
  {
    name: 'Bangkok',
    countryIso2: 'TH',
    adminRegion: 'Bangkok',
    population: 10539000,
    latitude: 13.7563,
    longitude: 100.5018,
  },
  {
    name: 'Kuala Lumpur',
    countryIso2: 'MY',
    adminRegion: 'Kuala Lumpur',
    population: 1788000,
    latitude: 3.139,
    longitude: 101.6869,
  },
  {
    name: 'Jakarta',
    countryIso2: 'ID',
    adminRegion: 'Jakarta',
    population: 10562088,
    latitude: -6.2088,
    longitude: 106.8456,
  },
  {
    name: 'Manila',
    countryIso2: 'PH',
    adminRegion: 'Metro Manila',
    population: 1780148,
    latitude: 14.5995,
    longitude: 120.9842,
  },
  {
    name: 'Ho Chi Minh City',
    countryIso2: 'VN',
    adminRegion: 'Ho Chi Minh City',
    population: 8993082,
    latitude: 10.8231,
    longitude: 106.6297,
    aliases: ['Saigon', 'HCMC'],
  },
  {
    name: 'Hanoi',
    countryIso2: 'VN',
    adminRegion: 'Hanoi',
    population: 8053663,
    latitude: 21.0285,
    longitude: 105.8542,
  },
  {
    name: 'Taipei',
    countryIso2: 'TW',
    adminRegion: 'Taipei',
    population: 2602418,
    latitude: 25.033,
    longitude: 121.5654,
  },
  {
    name: 'Mumbai',
    countryIso2: 'IN',
    adminRegion: 'Maharashtra',
    population: 12442373,
    latitude: 19.076,
    longitude: 72.8777,
    aliases: ['Bombay'],
  },
  {
    name: 'Delhi',
    countryIso2: 'IN',
    adminRegion: 'Delhi',
    population: 16787941,
    latitude: 28.6139,
    longitude: 77.209,
    aliases: ['New Delhi'],
  },
  {
    name: 'Bangalore',
    countryIso2: 'IN',
    adminRegion: 'Karnataka',
    population: 12409999,
    latitude: 12.9716,
    longitude: 77.5946,
    aliases: ['Bengaluru'],
  },
  {
    name: 'Hyderabad',
    countryIso2: 'IN',
    adminRegion: 'Telangana',
    population: 10404000,
    latitude: 17.385,
    longitude: 78.4867,
  },
  {
    name: 'Chennai',
    countryIso2: 'IN',
    adminRegion: 'Tamil Nadu',
    population: 10972000,
    latitude: 13.0827,
    longitude: 80.2707,
    aliases: ['Madras'],
  },
  {
    name: 'Kolkata',
    countryIso2: 'IN',
    adminRegion: 'West Bengal',
    population: 14974073,
    latitude: 22.5726,
    longitude: 88.3639,
    aliases: ['Calcutta'],
  },
  {
    name: 'Pune',
    countryIso2: 'IN',
    adminRegion: 'Maharashtra',
    population: 3124458,
    latitude: 18.5204,
    longitude: 73.8567,
  },
  {
    name: 'Ahmedabad',
    countryIso2: 'IN',
    adminRegion: 'Gujarat',
    population: 5577940,
    latitude: 23.0225,
    longitude: 72.5714,
  },
  {
    name: 'Islamabad',
    countryIso2: 'PK',
    adminRegion: 'Islamabad Capital Territory',
    population: 1014825,
    latitude: 33.6844,
    longitude: 73.0479,
  },
  {
    name: 'Karachi',
    countryIso2: 'PK',
    adminRegion: 'Sindh',
    population: 14910352,
    latitude: 24.8607,
    longitude: 67.0011,
  },
  {
    name: 'Lahore',
    countryIso2: 'PK',
    adminRegion: 'Punjab',
    population: 11126285,
    latitude: 31.5204,
    longitude: 74.3587,
  },
  {
    name: 'Dhaka',
    countryIso2: 'BD',
    adminRegion: 'Dhaka',
    population: 21000000,
    latitude: 23.8103,
    longitude: 90.4125,
  },
  {
    name: 'Colombo',
    countryIso2: 'LK',
    adminRegion: 'Western Province',
    population: 752993,
    latitude: 6.9271,
    longitude: 79.8612,
  },
  {
    name: 'Kathmandu',
    countryIso2: 'NP',
    adminRegion: 'Bagmati',
    population: 975453,
    latitude: 27.7172,
    longitude: 85.324,
  },
  {
    name: 'Yangon',
    countryIso2: 'MM',
    adminRegion: 'Yangon',
    population: 5214000,
    latitude: 16.8661,
    longitude: 96.1951,
    aliases: ['Rangoon'],
  },
  {
    name: 'Phnom Penh',
    countryIso2: 'KH',
    adminRegion: 'Phnom Penh',
    population: 2129371,
    latitude: 11.5564,
    longitude: 104.9282,
  },
  {
    name: 'Vientiane',
    countryIso2: 'LA',
    adminRegion: 'Vientiane',
    population: 820000,
    latitude: 17.9757,
    longitude: 102.6331,
  },
  {
    name: 'Ulaanbaatar',
    countryIso2: 'MN',
    adminRegion: 'Ulaanbaatar',
    population: 1442272,
    latitude: 47.8864,
    longitude: 106.9057,
  },
  {
    name: 'Almaty',
    countryIso2: 'KZ',
    adminRegion: 'Almaty',
    population: 1916822,
    latitude: 43.222,
    longitude: 76.8512,
  },
  {
    name: 'Tashkent',
    countryIso2: 'UZ',
    adminRegion: 'Tashkent',
    population: 2571668,
    latitude: 41.2995,
    longitude: 69.2401,
  },
  {
    name: 'Baku',
    countryIso2: 'AZ',
    adminRegion: 'Baku',
    population: 2300500,
    latitude: 40.4093,
    longitude: 49.8671,
  },
  {
    name: 'Tbilisi',
    countryIso2: 'GE',
    adminRegion: 'Tbilisi',
    population: 1201500,
    latitude: 41.7151,
    longitude: 44.8271,
  },
  {
    name: 'Yerevan',
    countryIso2: 'AM',
    adminRegion: 'Yerevan',
    population: 1075800,
    latitude: 40.1811,
    longitude: 44.5136,
  },
  {
    name: 'Tehran',
    countryIso2: 'IR',
    adminRegion: 'Tehran',
    population: 8693706,
    latitude: 35.6892,
    longitude: 51.389,
  },
  {
    name: 'Baghdad',
    countryIso2: 'IQ',
    adminRegion: 'Baghdad',
    population: 8765000,
    latitude: 33.3152,
    longitude: 44.3661,
  },
  {
    name: 'Damascus',
    countryIso2: 'SY',
    adminRegion: 'Damascus',
    population: 1754000,
    latitude: 33.5138,
    longitude: 36.2765,
  },
  {
    name: "Sana'a",
    countryIso2: 'YE',
    adminRegion: "Sana'a",
    population: 2957000,
    latitude: 15.3694,
    longitude: 44.191,
    aliases: ['Sanaa'],
  },

  // Africa
  {
    name: 'Cape Town',
    countryIso2: 'ZA',
    adminRegion: 'Western Cape',
    population: 4618000,
    latitude: -33.9249,
    longitude: 18.4241,
  },
  {
    name: 'Johannesburg',
    countryIso2: 'ZA',
    adminRegion: 'Gauteng',
    population: 5636000,
    latitude: -26.2041,
    longitude: 28.0473,
  },
  {
    name: 'Durban',
    countryIso2: 'ZA',
    adminRegion: 'KwaZulu-Natal',
    population: 3442361,
    latitude: -29.8587,
    longitude: 31.0218,
  },
  {
    name: 'Addis Ababa',
    countryIso2: 'ET',
    adminRegion: 'Addis Ababa',
    population: 3480000,
    latitude: 9.145,
    longitude: 38.7617,
  },
  {
    name: 'Nairobi',
    countryIso2: 'KE',
    adminRegion: 'Nairobi',
    population: 4735000,
    latitude: -1.2921,
    longitude: 36.8219,
  },
  {
    name: 'Dar es Salaam',
    countryIso2: 'TZ',
    adminRegion: 'Dar es Salaam',
    population: 6048000,
    latitude: -6.7924,
    longitude: 39.2083,
  },
  {
    name: 'Kampala',
    countryIso2: 'UG',
    adminRegion: 'Kampala',
    population: 1680600,
    latitude: 0.3476,
    longitude: 32.5825,
  },
  {
    name: 'Accra',
    countryIso2: 'GH',
    adminRegion: 'Greater Accra',
    population: 2388000,
    latitude: 5.6037,
    longitude: -0.187,
  },
  {
    name: 'Lagos',
    countryIso2: 'NG',
    adminRegion: 'Lagos',
    population: 15388000,
    latitude: 6.5244,
    longitude: 3.3792,
  },
  {
    name: 'Abuja',
    countryIso2: 'NG',
    adminRegion: 'Federal Capital Territory',
    population: 1235880,
    latitude: 9.0765,
    longitude: 7.3986,
  },
  {
    name: 'Dakar',
    countryIso2: 'SN',
    adminRegion: 'Dakar',
    population: 1438725,
    latitude: 14.7167,
    longitude: -17.4677,
  },
  {
    name: 'Abidjan',
    countryIso2: 'CI',
    adminRegion: 'Lagunes',
    population: 4980000,
    latitude: 5.36,
    longitude: -4.0083,
  },
  {
    name: 'Douala',
    countryIso2: 'CM',
    adminRegion: 'Littoral',
    population: 2768000,
    latitude: 4.0511,
    longitude: 9.7679,
  },
  {
    name: 'Luanda',
    countryIso2: 'AO',
    adminRegion: 'Luanda',
    population: 8613000,
    latitude: -8.8383,
    longitude: 13.2344,
  },
  {
    name: 'Maputo',
    countryIso2: 'MZ',
    adminRegion: 'Maputo',
    population: 1191619,
    latitude: -25.9692,
    longitude: 32.5732,
  },
  {
    name: 'Antananarivo',
    countryIso2: 'MG',
    adminRegion: 'Antananarivo',
    population: 1391433,
    latitude: -18.8792,
    longitude: 47.5079,
  },
  {
    name: 'Port Louis',
    countryIso2: 'MU',
    adminRegion: 'Port Louis',
    population: 147066,
    latitude: -20.1609,
    longitude: 57.5012,
  },
  {
    name: 'Victoria',
    countryIso2: 'SC',
    adminRegion: 'Mahé',
    population: 26420,
    latitude: -4.6191,
    longitude: 55.4513,
  },

  // Latin America
  {
    name: 'São Paulo',
    countryIso2: 'BR',
    adminRegion: 'São Paulo',
    population: 12325232,
    latitude: -23.5505,
    longitude: -46.6333,
    aliases: ['Sao Paulo'],
  },
  {
    name: 'Rio de Janeiro',
    countryIso2: 'BR',
    adminRegion: 'Rio de Janeiro',
    population: 6747815,
    latitude: -22.9068,
    longitude: -43.1729,
  },
  {
    name: 'Brasília',
    countryIso2: 'BR',
    adminRegion: 'Federal District',
    population: 3055149,
    latitude: -15.7942,
    longitude: -47.8822,
  },
  {
    name: 'Salvador',
    countryIso2: 'BR',
    adminRegion: 'Bahia',
    population: 2902927,
    latitude: -12.9714,
    longitude: -38.5014,
  },
  {
    name: 'Fortaleza',
    countryIso2: 'BR',
    adminRegion: 'Ceará',
    population: 2684142,
    latitude: -3.7319,
    longitude: -38.5267,
  },
  {
    name: 'Belo Horizonte',
    countryIso2: 'BR',
    adminRegion: 'Minas Gerais',
    population: 2512070,
    latitude: -19.9167,
    longitude: -43.9345,
  },
  {
    name: 'Mexico City',
    countryIso2: 'MX',
    adminRegion: 'Mexico City',
    population: 9209944,
    latitude: 19.4326,
    longitude: -99.1332,
    aliases: ['Ciudad de México', 'CDMX'],
  },
  {
    name: 'Guadalajara',
    countryIso2: 'MX',
    adminRegion: 'Jalisco',
    population: 1495182,
    latitude: 20.6597,
    longitude: -103.3496,
  },
  {
    name: 'Monterrey',
    countryIso2: 'MX',
    adminRegion: 'Nuevo León',
    population: 1135512,
    latitude: 25.6866,
    longitude: -100.3161,
  },
  {
    name: 'Buenos Aires',
    countryIso2: 'AR',
    adminRegion: 'Buenos Aires',
    population: 3075646,
    latitude: -34.6118,
    longitude: -58.396,
  },
  {
    name: 'Córdoba',
    countryIso2: 'AR',
    adminRegion: 'Córdoba',
    population: 1614668,
    latitude: -31.4201,
    longitude: -64.1888,
  },
  {
    name: 'Santiago',
    countryIso2: 'CL',
    adminRegion: 'Santiago Metropolitan',
    population: 7000000,
    latitude: -33.4489,
    longitude: -70.6693,
  },
  {
    name: 'Bogotá',
    countryIso2: 'CO',
    adminRegion: 'Cundinamarca',
    population: 7181468,
    latitude: 4.711,
    longitude: -74.0721,
    aliases: ['Bogota'],
  },
  {
    name: 'Medellín',
    countryIso2: 'CO',
    adminRegion: 'Antioquia',
    population: 2542542,
    latitude: 6.2476,
    longitude: -75.5658,
    aliases: ['Medellin'],
  },
  {
    name: 'Lima',
    countryIso2: 'PE',
    adminRegion: 'Lima',
    population: 9759046,
    latitude: -12.0464,
    longitude: -77.0428,
  },
  {
    name: 'Quito',
    countryIso2: 'EC',
    adminRegion: 'Pichincha',
    population: 2011388,
    latitude: -0.1807,
    longitude: -78.4678,
  },
  {
    name: 'Caracas',
    countryIso2: 'VE',
    adminRegion: 'Distrito Capital',
    population: 3221956,
    latitude: 10.4806,
    longitude: -66.9036,
  },
  {
    name: 'Montevideo',
    countryIso2: 'UY',
    adminRegion: 'Montevideo',
    population: 1319108,
    latitude: -34.9011,
    longitude: -56.1645,
  },
  {
    name: 'Asunción',
    countryIso2: 'PY',
    adminRegion: 'Asunción',
    population: 524190,
    latitude: -25.2637,
    longitude: -57.5759,
    aliases: ['Asuncion'],
  },
  {
    name: 'La Paz',
    countryIso2: 'BO',
    adminRegion: 'La Paz',
    population: 816044,
    latitude: -16.5,
    longitude: -68.15,
  },
  {
    name: 'Panama City',
    countryIso2: 'PA',
    adminRegion: 'Panama',
    population: 880691,
    latitude: 8.9824,
    longitude: -79.5199,
    aliases: ['Panama'],
  },
  {
    name: 'San José',
    countryIso2: 'CR',
    adminRegion: 'San José',
    population: 333288,
    latitude: 9.9281,
    longitude: -84.0907,
    aliases: ['San Jose'],
  },
  {
    name: 'Guatemala City',
    countryIso2: 'GT',
    adminRegion: 'Guatemala',
    population: 2934841,
    latitude: 14.6349,
    longitude: -90.5069,
    aliases: ['Guatemala'],
  },
  {
    name: 'Tegucigalpa',
    countryIso2: 'HN',
    adminRegion: 'Francisco Morazán',
    population: 1288750,
    latitude: 14.0723,
    longitude: -87.1921,
  },
  {
    name: 'San Salvador',
    countryIso2: 'SV',
    adminRegion: 'San Salvador',
    population: 316090,
    latitude: 13.6929,
    longitude: -89.2182,
  },
  {
    name: 'Managua',
    countryIso2: 'NI',
    adminRegion: 'Managua',
    population: 1028808,
    latitude: 12.1364,
    longitude: -86.2514,
  },
  {
    name: 'Santo Domingo',
    countryIso2: 'DO',
    adminRegion: 'Distrito Nacional',
    population: 2201941,
    latitude: 18.4861,
    longitude: -69.9312,
  },
  {
    name: 'Kingston',
    countryIso2: 'JM',
    adminRegion: 'Kingston',
    population: 937700,
    latitude: 18.0179,
    longitude: -76.8099,
  },
  {
    name: 'Port of Spain',
    countryIso2: 'TT',
    adminRegion: 'Port of Spain',
    population: 37074,
    latitude: 10.6549,
    longitude: -61.5019,
  },
  {
    name: 'Bridgetown',
    countryIso2: 'BB',
    adminRegion: 'Saint Michael',
    population: 110000,
    latitude: 13.0975,
    longitude: -59.6145,
  },
  {
    name: 'Nassau',
    countryIso2: 'BS',
    adminRegion: 'New Providence',
    population: 274400,
    latitude: 25.0479,
    longitude: -77.3554,
  },
];

async function populateLocations() {
  try {
    await testConnection();
    console.log('🔄 Starting location population...');

    // Clear existing data
    console.log('Clearing existing location data...');
    await query('DELETE FROM apply_cities');
    await query('DELETE FROM apply_countries');

    // Insert countries
    console.log(`Inserting ${countries.length} countries...`);
    const countryMap = new Map<string, string>(); // iso2 -> id

    for (const country of countries) {
      const normalizedKey = normalizeText(country.name);
      const result = await query<{ id: string }>(
        `INSERT INTO apply_countries (name, iso2, iso3, aliases, normalized_key)
         VALUES ($1, $2, $3, $4, $5)
         RETURNING id`,
        [
          country.name,
          country.iso2,
          country.iso3,
          country.aliases,
          normalizedKey,
        ]
      );
      countryMap.set(country.iso2, result.rows[0].id);
    }

    console.log(`✅ Inserted ${countries.length} countries`);

    // Insert cities
    console.log(`Inserting ${cities.length} cities...`);
    let inserted = 0;
    let skipped = 0;

    for (const city of cities) {
      const countryId = countryMap.get(city.countryIso2);
      if (!countryId) {
        console.warn(
          `Skipping city ${city.name} - country ${city.countryIso2} not found`
        );
        skipped++;
        continue;
      }

      const normalizedKey = normalizeText(city.name);
      await query(
        `INSERT INTO apply_cities (name, country_id, admin_region, population, latitude, longitude, aliases, normalized_key)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
         ON CONFLICT (normalized_key, country_id) DO NOTHING`,
        [
          city.name,
          countryId,
          city.adminRegion || null,
          city.population || null,
          city.latitude || null,
          city.longitude || null,
          city.aliases || [],
          normalizedKey,
        ]
      );
      inserted++;
    }

    console.log(`✅ Inserted ${inserted} cities (${skipped} skipped)`);
    console.log('✅ Location population completed successfully');
  } catch (error) {
    console.error('❌ Location population failed:', error);
    throw error;
  }
}

// Run if called directly
if (require.main === module) {
  populateLocations()
    .then(() => {
      console.log('Done');
      process.exit(0);
    })
    .catch(error => {
      console.error('Error:', error);
      process.exit(1);
    });
}

export { populateLocations };
